[package]
name = "temp_test"
version = "0.1.0"
edition = "2021"


[dependencies]
rusty-fork = { path = "../rusty-fork" }
tempfile = "^3"
temp_test_derive = { path = "derive"}

[dev-dependencies]
cmd_lib = "1.3.0"